
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
    version: blue  # Initially point to blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-blue-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
    version: blue
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-green-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
    version: green
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
